[package]
name = "mvr"
version = "0.1.0"
authors = ["Jeremy Stucki <jeremy@myelin.ch>"]
edition = "2018"

[dependencies]
clap = "2.33"
nom = "5.0"
either = "1.5"
itertools = "0.8"
nameof = "1.1"
mockiato = "0.9.5"
glob = "0.3"
